[workspace]
members = ["blocks-frontend"]

[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barrage = "0.2.1"
ureq = "2.4.0"
vial = "0.1.9"
ws = "0.9.2"
